################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

infer_config {
  unique_id: 4
  gpu_ids: 0
  max_batch_size: 4
  backend {
    triton {
      model_name: "poseclassificationnet"
      version: -1
      model_repo {
        root: "../../../models"
        strict_model_config: true
      }
    }
    output_mem_type: MEMORY_TYPE_DEFAULT
  }

  input_tensor_from_meta {
    is_first_dim_batch: true
  }

  postprocess {
    classification {
      custom_parse_classifier_func: "NvDsParseCustomPoseClassification"
      threshold: 0.51
    }
  }

  custom_lib {
    path: "../../../apps/tao_others/deepstream-pose-classification/infer_pose_classification_parser/libnvdsinfer_pose_classfication_parser.so"
  }

  extra {
    output_buffer_pool_size: 4
  }
}

output_control {
  output_tensor_meta: true
}

