/*
 * SPDX-FileCopyrightText: Copyright (c) 2019-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __GST_NVOF_VISUAL_H__
#define __GST_NVOF_VISUAL_H__

#include <gst/base/gstbasetransform.h>
#include <gst/video/video.h>

#include <cuda.h>
#include <cuda_runtime.h>

/* Package and library details required for plugin_init */
#define PACKAGE "nvofvisual"
#define VERSION "1.0"
#define LICENSE "Proprietary"
#define DESCRIPTION "NVIDIA opticalflow visualization plugin for integration with DeepStream on DGPU"
#define BINARY_PACKAGE "NVIDIA DeepStream Optical Flow Visualization Plugin"
#define URL "http://nvidia.com/"


G_BEGIN_DECLS
/* Standard boilerplate stuff */
typedef struct _GstNvOFVisual GstNvOFVisual;
typedef struct _GstNvOFVisualClass GstNvOFVisualClass;

/* Standard boilerplate stuff */
#define GST_TYPE_NV_OF_VISUAL (gst_nvof_visual_get_type())
#define GST_NV_OF_VISUAL(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj),GST_TYPE_NV_OF_VISUAL,GstNvOFVisual))
#define GST_NV_OF_VISUAL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass),GST_TYPE_NV_OF_VISUAL,GstNvOFVisualClass))
#define GST_NV_OF_VISUAL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), GST_TYPE_NV_OF_VISUAL, GstNvOFVisualClass))
#define GST_IS_NV_OF_VISUAL(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj),GST_TYPE_NV_OF_VISUAL))
#define GST_IS_NV_OF_VISUAL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass),GST_TYPE_NV_OF_VISUAL))
#define GST_NV_OF_VISUAL_CAST(obj)  ((GstNvOFVisual *)(obj))

struct _GstNvOFVisual
{
  GstBaseTransform base_trans;

  // Unique ID of the element. The labels generated by the element will be
  // updated at index `unique_id` of attr_info array in NvDsObjectParams.
  guint unique_id;

  // Frame number of the current input buffer
  guint64 frame_num;

  // Input video info (resolution, color format, framerate, etc)
  GstVideoInfo video_info;

  // Resolution at which frames/objects should be processed
  gint output_width;
  gint output_height;

  // GPU ID on which we expect to execute the task
  guint gpu_id;

  // Buffer pool size used for optical flow output
  guint pool_size;

  // Size of the grid in the picture that shares the same optical flow vector
  gint block_size_x;
  gint block_size_y;

  guint max_buffers;
  gint batch_size;
  guint num_batch_buffers;

  gint input_feature;
  gint output_feature;
  gint cuda_mem_type;
  GstVideoFormat input_fmt;
  GstVideoFormat output_fmt;

  GstVideoInfo in_info;
  GstVideoInfo out_info;

  GstCaps *sinkcaps;
  GstCaps *srccaps;

  GstBufferPool *pool;

  cudaStream_t *streams_array;
  //void *streams_array;
};

// Boiler plate stuff
struct _GstNvOFVisualClass
{
  GstBaseTransformClass parent_class;
};

GType gst_nvof_visual_get_type (void);

G_END_DECLS
#endif /* __GST_NVOF_VISUAL_H__ */
