/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __GST_NVDSFRAMESELECTOR_H__
#define __GST_NVDSFRAMESELECTOR_H__

#include <gst/base/gstbasetransform.h>
#include <gst/video/video.h>

#include <cuda.h>
#include <cuda_runtime.h>
#include "nvbufsurface.h"

#include <unordered_map>

/* Package and library details required for plugin_init */
#define PACKAGE "nvdsframeselector"
#define VERSION "1.0"
#define LICENSE "Proprietary"
#define DESCRIPTION "NVIDIA frame selector plugin for integration with DeepStream on DGPU"
#define BINARY_PACKAGE "NVIDIA DeepStream 3rdparty IP integration frame selector plugin"
#define URL "http://nvidia.com/"


G_BEGIN_DECLS
/* Standard boilerplate stuff */
typedef struct _GstNvDsFrameSelector GstNvDsFrameSelector;
typedef struct _GstNvDsFrameSelectorClass GstNvDsFrameSelectorClass;

/* Standard boilerplate stuff */
#define GST_TYPE_NVDS_FRAME_SELECTOR (gst_nvds_frame_selector_get_type())
#define GST_NVDS_FRAME_SELECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj),GST_TYPE_NVDS_FRAME_SELECTOR,GstNvDsFrameSelector))
#define GST_NVDS_FRAME_SELECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass),GST_TYPE_NVDS_FRAME_SELECTOR,GstNvDsFrameSelectorClass))
#define GST_NVDS_FRAME_SELECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), GST_TYPE_NVDS_FRAME_SELECTOR, GstNvDsFrameSelectorClass))
#define GST_IS_NVDS_FRAME_SELECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj),GST_TYPE_NVDS_FRAME_SELECTOR))
#define GST_IS_NVDS_FRAME_SELECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass),GST_TYPE_NVDS_FRAME_SELECTOR))
#define GST_NVDS_FRAME_SELECTOR_CAST(obj)  ((GstNvDsFrameSelector *)(obj))

struct _GstNvDsFrameSelector
{
  GstBaseTransform base_trans;

  // Unique ID of the element. The labels generated by the element will be
  // updated at index `unique_id` of attr_info array in NvDsObjectParams.
  guint unique_id;

  // Frame number of the current input buffer
  guint64 frame_num;
  // Total number of input frames received by this element
  guint64 input_frame_count;

  // Input video info (resolution, color format, framerate, etc)
  GstVideoInfo video_info;

  // Resolution at which frames/objects should be processed
  guint processing_width;
  guint processing_height;

  // GPU ID on which we expect to execute the task
  guint gpu_id;

  // Enable/disable frame selector
  gboolean enable_selector;

  // New configurable properties
  guint cache_size;                  // Number of frames to cache (default: 100)
  guint selection_count;             // Number of random frames to select (default: 10)
  gdouble percentage_threshold;      // Percentage threshold for frame filtering (0.0-100.0%)
  guint averaging_frames;            // Number of frames to average for SAD calculation
  guint exclusion_range;             // +/- range value for frame exclusion in selection algorithm
  gint frame_selection_algorithm;    // Frame selection algorithm to use (may be modified by motion detection)
  gint user_frame_selection_algorithm; // User-configured algorithm (preserved for reset each chunk)
  gboolean bypass_mode;              // Bypass mode to pass all frames through without selection
  guint optical_flow_interval;       // Analyze every Nth frame for optical flow motion detection (default: 15)
  gboolean enable_motion_detection;  // Enable/disable optical flow motion detection (default: TRUE)
  gdouble source_fps;                // Native stream fps (set by upstream). Used to normalize OF motion
                                     // to px-per-source-frame via frame PTS, making motion classification
                                     // invariant to input decimation. <=0 → fall back to frame-count.
  gint64 chunk_first_in_us;          // Monotonic time (us) of first input frame of the current chunk;
                                     // 0 = no chunk in progress. Used to log fselect residency
                                     // (first-frame-in → last-frame-out) per chunk.
  gint64 chunk_eos_us;               // Monotonic time (us) of EOS arrival (= last input frame received).
                                     // Splits residency into input/decode phase (first-in→EOS) and
                                     // selection phase (EOS→last-out, i.e. OF+SAD+selection+output).
  gint64 chunk_sad_us;               // Accumulated wall time (us) spent in per-frame SAD this chunk.
                                     // Lets the input-phase be split into decode/cache vs SAD.

  // Frame buffer storage
  NvBufSurface **cached_frames;      // Dynamic array to store cached frames
  guint *sad_values;                 // Dynamic array to store SAD values for each cached frame
  GstClockTime *cached_timestamps;   // Dynamic array to store timestamps for each cached frame
  guint64 *cached_frame_numbers;     // Dynamic array to store frame numbers for each cached frame
  guint cached_frame_count;          // Current number of cached frames
  guint cache_index;                 // Current index in circular buffer

  // Previous frame for SAD computation
  NvBufSurface *previous_frame;      // Previous frame for SAD comparison

  // Output state management
  gboolean is_outputting;            // TRUE when sending highest SAD frames
  guint output_count;                // Current count of frames sent
  guint *selected_indices;           // Dynamic array of selected frame indices (sorted by SAD)
  guint actual_selected_count;       // Actual number of frames selected (may be less than selection_count)

  // CUDA resources for SAD computation
  cudaStream_t cuda_stream;          // CUDA stream for async operations
  unsigned int *d_partial_sums;      // Pre-allocated device memory for partial sums
  unsigned int *h_partial_sums;      // Pre-allocated pinned host memory for partial sums
  guint max_blocks;                  // Maximum number of blocks allocated

  // Motion detection
  gboolean motion_detector_initialized;  // Motion detector initialization flag
  void *motion_detector_handle;          // Per-instance motion detector handle
  gint of_grid_cells;                    // Total OF grid cells at the current resolution
                                         // (from the motion verdict); used to make the
                                         // moving-cell COUNT thresholds resolution-invariant.
  guint eff_of_interval;                 // Effective OF sample interval actually used this chunk.
                                         // Equals optical_flow_interval when that is >=1; when it is
                                         // 0 (auto) it is derived from the received frame rate to hold
                                         // the OF gap near ~0.5s. Shared by the analysis stride and the
                                         // OF-only selector so both read sample_moving_cells[] alike.

  gdouble  of_tighten;                   // Tighten factor applied to the motion-scaled frame count
                                         // (e.g. 0.5 → halve the count, dropping the weakest frames).
                                         // Corresponds to OF_ONLY_TIGHTEN. Range (0, 1]. Default 0.5.
                                         // Env NVDS_FSELECT_OF_TIGHTEN overrides this at runtime.

  gboolean equidistant_output;           // When TRUE, replace whatever frames the selection algorithm
                                         // chose with equidistant frames spanning the same chunk.
                                         // The COUNT is still determined by the algorithm (OF/BASIC/
                                         // RANGE_BASED); only the positions become evenly spaced.

};

// Boiler plate stuff
struct _GstNvDsFrameSelectorClass
{
  GstBaseTransformClass parent_class;
};

GType gst_nvds_frame_selector_get_type (void);

G_END_DECLS
#endif /* __GST_NVDSFRAMESELECTOR_H__ */
