################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################
#
#######################################################################################################
# this  Makefile is to be used to build the test application to exercise the sample azure device client protocol adaptor
CXX:=g++
DS_INC:= ../../../../../includes

NVDS_VERSION?=9.0

DS_LIB:=/opt/nvidia/deepstream/deepstream-$(NVDS_VERSION)/lib/

SYNC_SEND_BIN:= test_azure_proto_sync
ASYNC_SEND_BIN:= test_azure_proto_async

SYNC_SEND_SRCS:=test_azure_proto_sync.c
ASYNC_SEND_SRCS:=test_azure_proto_async.c

CXXFLAGS:= -I$(DS_INC) -rdynamic
LDFLAGS:= -L$(DS_LIB) -ldl -lpthread -Wl,-rpath=$(DS_LIB)

default: all

all: $(SYNC_SEND_BIN) $(ASYNC_SEND_BIN)

$(SYNC_SEND_BIN) : $(SYNC_SEND_SRCS)
	$(CXX) -o $@ $^  $(CXXFLAGS) $(LDFLAGS)

$(ASYNC_SEND_BIN) : $(ASYNC_SEND_SRCS)
	$(CXX) -o $@ $^  $(CXXFLAGS) $(LDFLAGS)

clean:
	rm -rf $(SYNC_SEND_BIN) $(ASYNC_SEND_BIN)

