%YAML 1.2
################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

---
radius: 3.3
distance: 12.7
center: 0.5
can_width: 1.0
input_width: 870
input_height: 1200
crop_width: 500
target_x: 250

ref_image:
  perimeter: 1689
  image_path: data/reference_sample.grey
  image_format: GREY
  image_width: 2508
  image_height: 625