# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CXX:=g++
NVDS_VERSION:=9.1
DS_INC:= ../../../includes
DS_LIB:=/opt/nvidia/deepstream/deepstream-$(NVDS_VERSION)/lib

TEST_BIN:= test_msgbroker

TEST_SRCS:=test_msgbroker.cpp

CXXFLAGS:= -I$(DS_INC) -rdynamic
LDFLAGS:= -L$(DS_LIB) -lpthread -lnvds_msgbroker -ldl -Wl,-rpath=$(DS_LIB)

default: all

all: $(TEST_BIN)

$(TEST_BIN) : $(TEST_SRCS)
	$(CXX) -o $@ $^  $(CXXFLAGS) $(LDFLAGS)

clean:
	rm -rf $(TEST_BIN)

