// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: opentelemetry/proto/profiles/v1development/profiles.proto

#include "opentelemetry/proto/profiles/v1development/profiles.pb.h"
#include "opentelemetry/proto/profiles/v1development/profiles.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace opentelemetry {
namespace proto {
namespace profiles {
namespace v1development {

} // namespace opentelemetry
} // namespace proto
} // namespace profiles
} // namespace v1development

