/*
 * SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 *
 * NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 * property and proprietary rights in and to this material, related
 * documentation and any modifications thereto. Any use, reproduction,
 * disclosure or distribution of this material and related documentation
 * without an express license agreement from NVIDIA CORPORATION or
 * its affiliates is strictly prohibited.
 */

#ifndef __GST_NVREPLAY_H__
#define __GST_NVREPLAY_H__

#include <vector>

#include "nvbufsurftransform.h"
#include "gstnvdsmeta.h"
#include "gstnvreplay_lib.h"

/* Package and library details required for plugin_init */
#define PACKAGE "nvreplay"
#define VERSION "1.0.0"
#define LICENSE "Proprietary"
#define DESCRIPTION "Gstreamer plugin to load ground truth labels for evaluation"
#define BINARY_PACKAGE "Gstreamer nvreplay plugin"
#define URL "http://nvidia.com/"


G_BEGIN_DECLS
/* Standard boilerplate stuff */
typedef struct _GstNvReplay GstNvReplay;
typedef struct _GstNvReplayClass GstNvReplayClass;
typedef std::vector<float> Bbox;
/* Standard boilerplate stuff */
#define GST_TYPE_NVREPLAY (gst_nvreplay_get_type())
#define GST_NVREPLAY(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj),GST_TYPE_NVREPLAY,GstNvReplay))
#define GST_NVREPLAY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass),GST_TYPE_NVREPLAY,GstNvReplayClass))
#define GST_NVREPLAY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), GST_TYPE_NVREPLAY, GstNvReplayClass))
#define GST_IS_NVREPLAY(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj),GST_TYPE_NVREPLAY))
#define GST_IS_NVREPLAY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass),GST_TYPE_NVREPLAY))
#define GST_NVREPLAY_CAST(obj)  ((GstNvReplay *)(obj))

struct _GstNvReplay
{
  GstBaseTransform base_trans;

  // Unique ID of the element. The labels generated by the element will be
  // updated at index `unique_id` of attr_info array in NvDsObjectParams.
  guint unique_id;

  // Max frame number of each stream
  std::vector<guint64> max_frame_nums;
  char* max_frame_nums_str;

  // Input video info (resolution, color format, framerate, etc)
  GstVideoInfo video_info;

  // Resolution at which frames/objects should be processed
  guint label_width;
  guint label_height;

  // Amount of objects processed in single call to algorithm
  guint batch_size;

  // The directory of all the ground truth files
  char* label_dir;

  // The ground truth file names
  char* file_names;

  // Number of batches to skip for adding labels to meta data
  guint interval;

  // Counter for number of batches
  guint interval_counter;

  // Ground truth bboxes
  // <stream0< frame0<bbox0, bbox1>, frame1<bbox0, bbox1> ... >. stream1<> ... >
  std::vector<std::vector<std::vector<Bbox>>> label_bboxes;
};

// Boiler plate stuff
struct _GstNvReplayClass
{
  GstBaseTransformClass parent_class;
};

GType gst_nvreplay_get_type (void);

G_END_DECLS
#endif /* __GST_NVREPLAY_H__ */
