# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source:
  uri-list: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4
  ip-address: localhost
  port: 9010
  drop-pipeline-eos: 1
  live-source: 1
  max-batch-size: 10
  batched-push-timeout: 33333
  width: 1920
  height: 1080

tiler:
  width: 1280
  height: 720
  rows: 2
  columns: 5
  gpu-id: 0
  nvbuf-memory-type: 0
  square-seq-grid: 1
# streammux:
#   batch-size: 10
#   batched-push-timeout: 40000
#   width: 1920
#   height: 1080

# Inference using nvinfer:
primary-gie:
  plugin-type: 0
  config-file-path: ds_dynamic_demuxer_pgie_config.yml

## Inference using nvinferserver:
#primary-gie:
#  plugin-type: 1
#  config-file-path: ds_dynamic_demuxer_pgie_nvinferserver_config.txt
