# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

deepstream:
  nodes:
  - name: filesrc
    properties:
      location: /opt/nvidia/deepstream/deepstream/samples/streams/sample_720p.h264
    type: filesrc
  - name: h264parse
    type: h264parse
  - name: nvv4l2decoder
    type: nvv4l2decoder
  - name: nvstreammux
    properties:
      batch-size: 1
      height: 720
      width: 1280
    type: nvstreammux
  - name: infer
    properties:
      config-file-path: /opt/nvidia/deepstream/deepstream/sources/apps/sample_apps/deepstream-test4/dstest4_pgie_config.yml
    type: nvinfer
## Inference using nvinferserver: replace the above infer definition with below
#  - name: infer
#    type: nvinferserver 
#    properties:
#      config-file-path: /opt/nvidia/deepstream/deepstream/sources/apps/sample_apps/deepstream-test4/dstest4_pgie_nvinferserver_config.txt
  - name: nvvideoconvert
    type: nvvideoconvert
  - name: nvdsosd
    type: nvdsosd
  - name: tee
    type: tee
  - name: queue
    type: queue
  - name: queue1
    type: queue
  - name: nv3dsink
    type: nv3dsink
  - name: nvmsgconv
    properties:
      config: /opt/nvidia/deepstream/deepstream/sources/apps/sample_apps/deepstream-test4/dstest4_msgconv_config.yml
    type: nvmsgconv
  - name: nvmsgbroker
    properties:
      conn-str: localhost;9092
      proto-lib: /opt/nvidia/deepstream/deepstream/lib/libnvds_kafka_proto.so
      sync: false
      topic: test4app
    type: nvmsgbroker
  - name: addmessagemetaprobe
    type: add_message_meta_probe.add_message_meta_probe
  edges:
    filesrc: h264parse
    h264parse: nvv4l2decoder
    nvdsosd:
    - tee
    - addmessagemetaprobe
    infer.src: nvvideoconvert
    nvmsgconv: nvmsgbroker
    nvstreammux: infer
    nvv4l2decoder: nvstreammux
    nvvideoconvert: nvdsosd
    queue.src: nv3dsink
    queue1.src: nvmsgconv
    tee:
    - queue
    - queue1