################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################
---
- name: Format TensorRT sub-version into apt version pin
  set_fact:
    trt_sub_version_pin: "={{ trt_sub_version_prod }}*"
  when: trt_sub_version_prod != ''

- name: Install TensorRT packages
  apt:
    name:
      - libnvinfer{{ trt_version_prod }}{{ trt_sub_version_pin | default('') }}
      - libnvinfer-dev{{ trt_sub_version_pin | default('') }}
      - libnvinfer-plugin{{ trt_version_prod }}{{ trt_sub_version_pin | default('') }}
      - libnvinfer-plugin-dev{{ trt_sub_version_pin | default('') }}
      - libnvonnxparsers{{ trt_version_prod }}{{ trt_sub_version_pin | default('') }}
      - libnvonnxparsers-dev{{ trt_sub_version_pin | default('') }}
      - libnvinfer-lean{{ trt_version_prod }}{{ trt_sub_version_pin | default('') }}
      - libnvinfer-lean-dev{{ trt_sub_version_pin | default('') }}
      - libnvinfer-dispatch{{ trt_version_prod }}{{ trt_sub_version_pin | default('') }}
      - libnvinfer-dispatch-dev{{ trt_sub_version_pin | default('') }}
      - libnvinfer-vc-plugin{{ trt_version_prod }}{{ trt_sub_version_pin | default('') }}
      - libnvinfer-vc-plugin-dev{{ trt_sub_version_pin | default('') }}
      - libnvinfer-headers-dev{{ trt_sub_version_pin | default('') }}
      - libnvinfer-safe-headers-dev{{ trt_sub_version_pin | default('') }}
      - libnvinfer-headers-plugin-dev{{ trt_sub_version_pin | default('') }}
      - libnvinfer-headers-python-plugin-dev{{ trt_sub_version_pin | default('') }}
      - python3-libnvinfer{{ trt_sub_version_pin | default('') }}
      - python3-libnvinfer-dev{{ trt_sub_version_pin | default('') }}
      - python3-libnvinfer-dispatch{{ trt_sub_version_pin | default('') }}
      - python3-libnvinfer-lean{{ trt_sub_version_pin | default('') }}
      - libnvinfer-bin{{ trt_sub_version_pin | default('') }}
      - tensorrt{{ trt_sub_version_pin | default('') }}
      - tensorrt-libs{{ trt_sub_version_pin | default('') }}
      - tensorrt-dev{{ trt_sub_version_pin | default('') }}
    state: present
    update_cache: yes
  become: yes

- name: Install TensorRT Windows builder resource (x86_64 only)
  apt:
    name: libnvinfer-win-builder-resource{{ trt_version_prod }}{{ trt_sub_version_pin | default('') }}
    state: present
    update_cache: yes
  become: yes
  when: ansible_architecture == "x86_64"
