################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

source-list:
  list: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_720p.mp4

streammux:
  batch-size: 1
  width: 1920
  height: 1080
  batched-push-timeout: 4000000

primary-gie:
  #0:nvinfer, 1:nvinfeserver
  plugin-type: 0

  #peoplenet-transformer
  config-file-path: ../nvinfer/peoplenet_transformer_tao/pgie_peoplenet_transformer_tao_config.yml
  #config-file-path: ../triton/peoplenet_transformer_tao/pgie_peoplenet_transformer_tao_config.yml
  #config-file-path: ../triton-grpc/peoplenet_transformer_tao/pgie_peoplenet_transformer_tao_config.yml

eglsink:
  enable: 0

filesink:
  enable: 1
  #encoder type 0=Hardware 1=Software
  enc-type: 0

fakesink:
  enable: 0

tests:
  file-loop: 0
