/*
 * SPDX-FileCopyrightText: Copyright (c) 2020-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __GST_NVINFERBASE_H__
#define __GST_NVINFERBASE_H__

#include <gst/base/gstbasetransform.h>
#include <gst/video/video.h>
#include <gst/audio/audio.h>

#include <set>
#include <unordered_map>
#include <vector>
#include <memory>

#include "cuda_runtime_api.h"
#include "nvbufsurftransform.h"
#include <nvdsinfer_context.h>

#include "gstnvdsinfer.h"
#include "gstnvinfer_impl.h"
#include "gstnvdsmeta.h"

#include "nvtx3/nvToolsExt.h"

G_BEGIN_DECLS
/* Standard GStreamer boilerplate */
typedef struct _GstNvInferBase GstNvInferBase;
typedef struct _GstNvInferBaseClass GstNvInferBaseClass;
typedef struct _GstNvInferImpl GstNvInferImpl;

/* Standard GStreamer boilerplate */
#define GST_TYPE_NVINFERBASE (gst_nvinferbase_get_type())
#define GST_NVINFERBASE(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj),GST_TYPE_NVINFERBASE,GstNvInferBase))
#define GST_NVINFERBASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass),GST_TYPE_NVINFERBASE,GstNvInferBaseClass))
#define GST_NVINFERBASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), GST_TYPE_NVINFERBASE, GstNvInferBaseClass))
#define GST_IS_NVINFERBASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj),GST_TYPE_NVINFERBASE))
#define GST_IS_NVINFERBASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass),GST_TYPE_NVINFERBASE))
#define GST_NVINFERBASE_CAST(obj)  ((GstNvInferBase *)(obj))

/**
 * Enum for all GObject properties for the element.
 */
enum
{
  PROP_0,
  PROP_UNIQUE_ID,
  PROP_PROCESS_MODE,
  PROP_CONFIG_FILE_PATH,
  PROP_OPERATE_ON_GIE_ID,
  PROP_OPERATE_ON_CLASS_IDS,
  PROP_FILTER_OUT_CLASS_IDS,
  PROP_MODEL_ENGINEFILE,
  PROP_BATCH_SIZE,
  PROP_INTERVAL,
  PROP_GPU_DEVICE_ID,
  PROP_OUTPUT_WRITE_TO_FILE,
  PROP_OUTPUT_CALLBACK,
  PROP_OUTPUT_CALLBACK_USERDATA,
  PROP_OUTPUT_TENSOR_META,
  PROP_AUDIO_TRANSFORM,
  PROP_AUDIO_FRAME_SIZE,
  PROP_AUDIO_HOP_SIZE,
  PROP_CLASSIFIER_TYPE,
  PROP_LAST
};

/* nvinfer signals */
enum {
  /* Signal emitted to notify app about model update completion with
   * success/error messages. */
  SIGNAL_MODEL_UPDATED,
  LAST_SIGNAL,
};

extern guint gst_nvinfer_signals[LAST_SIGNAL];

/**
 * GstNvInferBase element structure.
 */
struct _GstNvInferBase
{
  /** Should be the first member when extending from GstBaseTransform. */
  GstBaseTransform base_trans;

  /** Boolean indicating if the config parsing was successful. */
  gboolean config_file_parse_successful;

  /** Maximum batch size. */
  guint max_batch_size;

  /**
   * Unique ID of the element. The labels generated by the element will be
   * updated at index `unique_id` of attr_info array in NvDsObjectParams. For
   * detectors, this value will be assigned to gie_unique_id of NvDsFrameMeta
   * meta structure attached by the element to identify the meta attached by
   * this element.
   */
  guint unique_id;

  const gchar *classifier_type;

  guint interval_counter;

  /** Processing Queue and related synchronization structures. */
  GQueue *process_queue;
  GMutex process_lock;
  GCond process_cond;
  GQueue *input_queue;

  /** Output thread. */
  GThread *output_thread;
  GThread *input_queue_thread;

  /** Boolean to signal output thread to stop. */
  gboolean stop;

  /** Network input resolution. */
  gint network_width;
  gint network_height;

  /** Path to the configuration file for this instance of gst-nvinfer. */
  gchar *config_file_path;

  /** GstFlowReturn returned by the latest buffer pad push. */
  GstFlowReturn last_flow_ret;

  /** ID of the GPU this element uses for conversions / inference. */
  guint gpu_id;

  /** Current batch number of the input batch. */
  gulong current_batch_num;

  /** Network input information. */
  NvDsInferNetworkInfo network_info;

  /** Vector of bound layers information. */
  std::vector<NvDsInferLayerInfo> *layers_info;

  /** Vector of bound output layers information. */
  std::vector<NvDsInferLayerInfo> *output_layers_info;

  /** Boolean indicating if the bound buffer contents should be written to file. */
  gboolean write_raw_buffers_to_file;

  /** Batch counter for writing buffer contents to file. */
  guint64 file_write_batch_num;

  /** Pointer to the callback function and userdata for application access to
   * the bound buffer contents. */
  gst_nvinfer_raw_output_generated_callback output_generated_callback;
  gpointer output_generated_userdata;

  /** Vector of booleans indicating if properties have been set through
   * GObject set method. */
  std::vector<gboolean> *is_prop_set;

  /** Boolean indicating if tensor outputs should be attached as meta on
   * GstBuffers. */
  gboolean output_tensor_meta;

  /** NVTX Domain. */
  nvtxDomainHandle_t nvtx_domain;

  GstNvInferImpl *impl;
};

/* GStreamer boilerplate. */
struct _GstNvInferBaseClass {
  GstBaseTransformClass parent_class;

  /** Signals */
  /** signal : model-update
    * err: int, error result, type NvDsInferStatus.
    * cfg_file: update cfg file.
    */
  void (*model_updated) (GstNvInferBase *, gint err, const gchar *cfg_file);

  gboolean (*start) (GstNvInferBase *base, NvDsInferContextInitParams *init_params);
  void (*stop) (GstNvInferBase *base);
  gboolean (*set_caps) (GstNvInferBase *base, GstCaps * incaps, GstCaps * outcaps);
  gboolean (*sink_event) (GstNvInferBase * base, GstEvent * event);
  void (*finalize) (GObject * object);

  GstFlowReturn (*process_input) (GstNvInferBase *base, GstBuffer *inbuf);
  gboolean (*process_output) (GstNvInferBase *base, GstNvInferBatch *batch, NvDsInferContextBatchOutput *batch_output, GstMiniObject * tensor_out_object);
  void (*attach_previous_metadata) (GstNvInferBase *base, GstNvInferBatch *batch);
  void (*clear_history) (GstNvInferBase *base);

  gboolean (*parse_other_attributes) (GstNvInferBase * base, GKeyFile * key_file, const gchar * group_name, const gchar * key);
  gboolean (*parse_other_groups) (GstNvInferBase * base, GKeyFile * key_file, NvDsInferContextInitParams *init_params);

  NvDsInferFormat (*get_default_infer_format) (GstNvInferBase *base);
  NvDsInferFormat (*get_input_format) (GstNvInferBase *base, GstNvInferBatch *batch);
  unsigned int (*get_input_pitch) (GstNvInferBase *base, GstNvInferBatch *batch);
  unsigned int (*get_output_buffer_pool_size) (GstNvInferBase *base);
  gboolean (*get_classifier_async_mode) (GstNvInferBase *base);
};

void gst_nvinfer_push_to_input_queue (GstNvInferBase *nvinfer, GstNvInferBatch *batch);

GType gst_nvinferbase_get_type (void);

G_END_DECLS

#endif /* __GST_NVINFERBASE_H__ */
